# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arianet < Formula
  desc "Command-line client for the Ariaservice cloud API"
  homepage "https://github.com/ariaservice/arianet-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.2/arianet_0.1.2_darwin_amd64.tar.gz"
      sha256 "c038035b9c0453314526f4378ed82e81d73a37dc08a21a1007a3578517986792"

      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.2/arianet_0.1.2_darwin_arm64.tar.gz"
      sha256 "aec1c9f7d3e03804fd1a877da0e31ace8045ca73e014c247f528d7433cf3e98a"

      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.2/arianet_0.1.2_linux_amd64.tar.gz"
      sha256 "9f20d2acbcdfb4f5ba48179bc77175f6a2a22c01eb6e37e400094b6967d3eab1"
      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.2/arianet_0.1.2_linux_arm64.tar.gz"
      sha256 "9e63c526d247226a9014c5c9d5d20deefc390e0725e06fd09a59cbbf50df774a"
      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/arianet version")
  end
end
