# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arianet < Formula
  desc "Command-line client for the Ariaservice cloud API"
  homepage "https://github.com/ariaservice/arianet-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.0/arianet_0.1.0_darwin_amd64.tar.gz"
      sha256 "c9e0c8729f7cd959aeab97850b9bf755cba05331defb8a308565a97f18fe436f"

      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.0/arianet_0.1.0_darwin_arm64.tar.gz"
      sha256 "a566c06749fb1232c987636b1cddfca97954ca6d8d2cddb5af65ab7760591a12"

      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.0/arianet_0.1.0_linux_amd64.tar.gz"
      sha256 "9b094d932748c04408fab63c905f6134ed8b3aaef121eea937dbb026be11946b"
      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.0/arianet_0.1.0_linux_arm64.tar.gz"
      sha256 "c3d668a31f47af88cc220c9c7ba72755b5477637a23994bd48a558215e0ad093"
      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/arianet version")
  end
end
