# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arianet < Formula
  desc "Command-line client for the Ariaservice cloud API"
  homepage "https://github.com/ariaservice/arianet-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.1/arianet_0.1.1_darwin_amd64.tar.gz"
      sha256 "579ac84ebe06f6a221bf60e444fb14c9419becc03fe4e266ac3082e2288218c0"

      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.1/arianet_0.1.1_darwin_arm64.tar.gz"
      sha256 "23863601e8098e7ee41bc63d922189e1218549b1fb32b5b6be1b1c9156164f78"

      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.1/arianet_0.1.1_linux_amd64.tar.gz"
      sha256 "42582a4428db6aa8d2f623c856e17c768bb6073db3271b70ff8d1de6c5379848"
      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariaservice/arianet-cli/releases/download/v0.1.1/arianet_0.1.1_linux_arm64.tar.gz"
      sha256 "35777b26da2630040185de3864b1e4b30b0a77afd174ba2d67ecb5943c2c4518"
      define_method(:install) do
        bin.install "arianet"
        bash_completion.install "completions/arianet.bash" => "arianet"
        zsh_completion.install "completions/_arianet"
        fish_completion.install "completions/arianet.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/arianet version")
  end
end
